### ISSUE TITLE
Instruction to build with own svgs?

### ISSUE THREAD

**Issue by yurayakimenko** [mirgj/cryptocurrency-icons-font#10]
Is there any way to build webfont by yourself without need to request your participation?

**Comment by mirgj** [comment]
hi @yurayakimenko not sure I understood your question. Can you elaborate more?

Anyway if you want to have your own svgs and reuse this project just feel free to fork it and place the files under src/svg

You can use the command you can see in the package.json to build the font: npm run build

**Comment by mirgj** [comment]
closing this as not clear, feel free to open a new issue if needed
