### ISSUE TITLE
New Cryptocurrencies

### ISSUE THREAD

**Issue by Paulsky** [mirgj/cryptocurrency-icons-font#3]
Hello,

This is one of the greatest collections of cryptocurrencies webfont icons I found so far! Thank you for this project.

How can I contribute / add new icons/coins to this project?

**Comment by mirgj** [comment]
Hi @Paulsky it's pretty easy just add the files here: https://github.com/mirgj/cryptocurrency-icons-font/tree/master/src/svg

once is done you can just run `npm run build` to build the fonts and svg map

**Comment by mirgj** [comment]
you can also fork this repo and do the changes, then you open a PR and I will take care to merge, build and publish a new version

**Comment by Paulsky** [comment]
Thank you @mirgj ! Sounds great. I will open a PR! Do you have any good resources to find the crypto SVG icons? Or do you create them yourself? I think they all should have the same style.

**Comment by mirgj** [comment]
I started this project over a year ago from a repo that contained a lot of cryptos SVGs  ( https://github.com/atomiclabs/cryptocurrency-icons ) some new SVG has been added by a few contributors and then I kept maintaining it.

The above repo evolved as well to add icons but I kept working on this here and there cause the webfont.

**Comment by Paulsky** [comment]
I understand! So this repo is in sync with https://github.com/atomiclabs/cryptocurrency-icons? Maybe it's a better idea to wait for new icons there, instead of adding all kinds of different icons with different styles?

**Comment by mirgj** [comment]
yes. Initially they didn't have any webfont so I added in my own repo here. Eventually somebody contributed there so now they also have a font if I'm not wrong. Before they had only svg.

In your case, maybe yes is better for you to contribute to that repo if you're going to create new svg

**Comment by Paulsky** [comment]
I don't think they have a CSS classed based system. So I would like to stick to this repo! But if I'm going to design the icons myself, I will first propose the icon in the other repo, so I can sync it back in this repo. Thank you! I will try to check frequently if these repo's are still in sync :)

**Comment by mirgj** [comment]
that's good! Anyway I just synced up like two days ago so for now are in sync :)

**Comment by Paulsky** [comment]
Yes, I already updated my local package. Thank you for that! :)
