### ISSUE TITLE
Algorand (ALGO) Inclusion

### ISSUE THREAD

**Issue by bchoubert** [mirgj/cryptocurrency-icons-font#8]
Coinbase just added this crypto in their API.
Description here: https://coinmarketcap.com/currencies/algorand/

I added an issue here: https://github.com/atomiclabs/cryptocurrency-icons/issues/341

Thanks for this awesome repo!

**Comment by bchoubert** [comment]
This icon was just included in the latest version of https://github.com/spothq/cryptocurrency-icons/issues/341 .

**Comment by mirgj** [comment]
@bchoubert this has been published on the latest version see #19
